# -*- coding: utf-8 -*-
"""FYP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NcNjTIl8YWbMFk0cxGpPT1tcdUuCBu3-
"""

!pip install transformers datasets evaluate
!pip install datasets
!pip install accelerate>=0.20.
!pip install huggingface_hub

# used for the login in huggingface
from huggingface_hub import notebook_login
notebook_login()

# load the dataset from the huggingface
from datasets import load_dataset
imdb = load_dataset("celikmus/symptom_text_to_disease_01")

imdb['train'].features

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

tokenized_imdb = imdb.map(preprocess_function, batched=True)

from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

import evaluate

accuracy = evaluate.load("accuracy")

import numpy as np

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return accuracy.compute(predictions=predictions, references=labels)

# used for the tokenization and detokenization

id2label = {
0 : 'emotional pain',
1 : 'hair falling out',
2 : 'heart hurts',
3 : 'infected wound',
4 : 'foot ache',
5 : 'shoulder pain',
6 : 'injury from sports',
7 : 'skin issue',
8 : 'stomach ache',
9 : 'knee pain',
10 : 'joint pain',
11 : 'hard to breath',
12 : 'head ache',
13 : 'body feels weak',
14 : 'feeling dizzy',
15 : 'back pain',
16 : 'open wound',
17 : 'Internal Medicine',
18 : 'blurry vision',
19 : 'acne',
20 : 'muscle pain',
21 : 'neck pain',
22 : 'cough',
23 : 'ear ache',
24 : 'feeling cold',
}

label2id = {
'emotional pain':0,
'hair falling out':1,
'heart hurts':2,
'infected wound':3,
'foot ache':4,
'shoulder pain':5,
'injury from sports':6,
'skin issue':7,
'stomach ache':8,
'knee pain':9,
'joint pain':10,
'hard to breath':11,
'head ache':12,
'body feels weak':13,
'feeling dizzy':14,
'back pain':15,
'open wound':16,
'Internal Medicine':17,
'blurry vision':18,
'acne':19,
'muscle pain':20,
'neck pain':21,
'cough':22,
'ear ache':23,
'feeling cold':24,
}

# loading the pre-trained model
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=25, id2label=id2label, label2id=label2id
)

# training arguments for the model training.

training_args = TrainingArguments(
    output_dir="my_hospital_reco",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    push_to_hub=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_imdb["train"],
    eval_dataset=tokenized_imdb["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

trainer.push_to_hub()

from transformers import pipeline

text = input("Enter your problems!!")
classifier = pipeline("sentiment-analysis", model="itsriya/my_hospital_reco")
result = classifier(text)
print(result[0]['label'])