# Generated by Django 4.2.9 on 2024-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_doctor_address_doctor_doctor_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(max_length=10),
        ),
    ]
