# Generated by Django 4.2.9 on 2024-01-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_profile',
            field=models.ImageField(upload_to='media/pictures', verbose_name='User Profile'),
        ),
    ]
