# Generated by Django 4.2.9 on 2024-03-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('blog_body', models.TextField(blank=True, max_length=3500, verbose_name='body')),
                ('blog_images', models.ImageField(upload_to='media/blog', verbose_name='Image for blog')),
                ('blog_date', models.DateField(auto_now_add=True, verbose_name='today_date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
