# Generated by Django 4.2.9 on 2024-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_images',
            field=models.ImageField(upload_to='media/media/blog/', verbose_name='Image for blog'),
        ),
    ]
