# Generated by Django 4.2.9 on 2024-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('blogs', '0002_alter_blogs_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_images',
            field=models.ImageField(upload_to='media/blog/', verbose_name='Image for blog'),
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=500, verbose_name='Hospital Name: ')),
                ('hospital_doctors', models.ManyToManyField(to='authentication.userprofile')),
            ],
        ),
    ]
