# Generated by Django 4.2.9 on 2024-04-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_blog_images_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_images',
            field=models.ImageField(blank=True, upload_to='media/blog/', verbose_name='Image for blog'),
        ),
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
