# Generated by Django 4.2.9 on 2024-04-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_hospital_hospital_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='User Email')),
                ('appointment_time', models.DateTimeField()),
                ('appointment_status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='requested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='authentication.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.userprofile')),
            ],
        ),
    ]
