# Generated by Django 4.2.9 on 2024-04-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='appointment_email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='appointment_name',
        ),
    ]
