# Generated by Django 4.2.9 on 2024-03-01 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerPost',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('offer_body', models.TextField(blank=True, max_length=2500, verbose_name='Body')),
                ('today_date', models.DateField(auto_now_add=True, verbose_name='today_date')),
                ('expiry_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='expiry_Date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
