# Generated by Django 4.2.9 on 2024-03-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerpost',
            old_name='offer_id',
            new_name='order_id',
        ),
    ]
