# Generated by Django 4.2.9 on 2024-03-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_offer_id_offerpost_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerpost',
            old_name='order_id',
            new_name='offer_id',
        ),
    ]
