# Generated by Django 4.2.9 on 2024-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_order_id_offerpost_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpost',
            name='offer_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
