# Generated by Django 4.2.9 on 2024-03-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_offerpost_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpost',
            name='offer_explanation',
            field=models.TextField(blank=True, max_length=2500, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='offer_location',
            field=models.CharField(blank=True, max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='offerpost',
            name='offer_body',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Body'),
        ),
    ]
