# Generated by Django 4.2.9 on 2024-03-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_offerpost_offer_explanation_offerpost_offer_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerpost',
            old_name='offer_explanation',
            new_name='offer_explaination',
        ),
    ]
