# Generated by Django 4.2.9 on 2024-04-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_offer_explanation_offerpost_offer_explaination'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpost',
            name='offer_picture',
            field=models.ImageField(null=True, upload_to='staic\\offerPost', verbose_name='Post Image'),
        ),
    ]
