# Generated by Django 4.2.9 on 2024-04-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_offerpost_offer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpost',
            name='offer_picture',
            field=models.ImageField(null=True, upload_to='staic/offerPost', verbose_name='Post Image'),
        ),
    ]
