# Generated by Django 4.2.9 on 2024-02-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('body', models.TextField(blank=True, max_length=2500, verbose_name='Body')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
