# Generated by Django 4.2.9 on 2024-03-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard',
            new_name='blog',
        ),
    ]
