# Generated by Django 5.0.1 on 2024-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor_username', models.CharField(blank=True, max_length=150, verbose_name='Doctor name')),
                ('Doctor_email', models.EmailField(blank=True, max_length=200, verbose_name='Doctor Email')),
                ('Doctor_profile', models.ImageField(upload_to='', verbose_name='Doctor Profile')),
                ('Doctor_address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('Doctor_password', models.CharField(blank=True, max_length=250, verbose_name='Password')),
                ('Doctor_status', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('hospital', 'Hospital')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital_username', models.CharField(blank=True, max_length=150, verbose_name='Hospital name')),
                ('Hospital_email', models.EmailField(blank=True, max_length=200, verbose_name='Hospital Email')),
                ('Hospital_contact', models.PositiveBigIntegerField(blank=True, verbose_name='Contact number')),
                ('Hospital_profile', models.ImageField(upload_to='', verbose_name='Hospital Profile')),
                ('Hospital_address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('Hospital_password', models.CharField(blank=True, max_length=250, verbose_name='Password')),
                ('Hospital_status', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('hospital', 'Hospital')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('User_email', models.EmailField(blank=True, max_length=200, unique=True, verbose_name='User Email')),
                ('User_contact', models.PositiveBigIntegerField(blank=True, verbose_name='Contact number')),
                ('User_profile', models.ImageField(upload_to='', verbose_name='User Profile')),
                ('User_address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('User_password', models.CharField(blank=True, max_length=100, verbose_name='Password')),
                ('User_status', models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('hospital', 'Hospital')], max_length=10)),
            ],
        ),
    ]
