# Generated by Django 4.2.9 on 2024-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('user_email', models.EmailField(blank=True, max_length=200, verbose_name='User Email')),
                ('user_contact', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Contact number')),
                ('user_profile', models.ImageField(upload_to='media', verbose_name='User Profile')),
                ('user_address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('user_password', models.CharField(blank=True, max_length=100, verbose_name='Password')),
                ('user_status', models.CharField(blank=True, max_length=25, verbose_name='Status')),
            ],
        ),
    ]
