# Generated by Django 4.2.9 on 2024-01-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_contact',
            new_name='user_contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_password',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_status',
            new_name='user_status',
        ),
    ]
