# Generated by Django 4.2.9 on 2024-04-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_speciality',
            field=models.CharField(blank=True, max_length=25, verbose_name='Status'),
        ),
    ]
