# Generated by Django 4.2.9 on 2024-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_user_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_speciality',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
