# Generated by Django 4.2.9 on 2024-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_user_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_specialists', models.CharField(blank=True, max_length=500, verbose_name='Hospital Speciality: ')),
                ('hospital_user', models.ManyToManyField(related_name='user_hospital_details', to='authentication.userprofile')),
            ],
        ),
    ]
