# Generated by Django 4.2.9 on 2024-02-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_contact',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Contact number'),
        ),
    ]
