# Generated by Django 4.2.9 on 2024-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
