# Generated by Django 4.2.9 on 2024-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_username_userprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Password'),
        ),
    ]
