# Generated by Django 4.2.9 on 2024-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_hospital_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_description',
            field=models.CharField(max_length=450, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_profile',
            field=models.ImageField(null=True, upload_to='media/hospital', verbose_name='Hospital Profile'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_specialists',
            field=models.CharField(max_length=500, null=True, verbose_name='Hospital Speciality: '),
        ),
    ]
